fix: Add retrocompatibility with Mobbex 2.x subscriptions
mobbexco/woocommerce-subscriptions pull request #41
Opened 2023-08-15 14:52 UTC by EMunozMobbex

2023-08-28 15:25 UTC, jlmobbex requested changes

2023-08-28 15:25 UTC, jlmobbex commented on mobbex-subs-for-woocommerce.php
> +            migrate_standalone_subs();
Este método no está en el código

2023-08-28 15:25 UTC, jlmobbex commented on mobbex-subs-for-woocommerce.php
> +            if (get_option('woocommerce-mobbex-version') < MOBBEX_VERSION)
`MOBBEX_VERSION` sería de la versión del plugin principal (checkout), no está definida en Mobbex subs.

2023-08-28 15:25 UTC, jlmobbex commented on mobbex-subs-for-woocommerce.php
> +            update_option('woocommerce-mobbex-version', MOBBEX_VERSION);
Hay que agregarle un nombre que refiera a subs

2023-08-28 15:25 UTC, jlmobbex commented on includes/helper.php
> +    public function migrate_subscriptions($order)
Yo lo nombraría `maybe_migrate_subscriptions` porque no siempre va a migrar las suscripciones (ej. si instalás el plugin por primera vez en la 3.0).

2023-08-28 15:25 UTC, jlmobbex commented on includes/helper.php
> +            ) {
Podés hacer la comprobación chequeando si get_post_meta está vacío (al terminar cada migración tendrías que dejarlas vacían en db). También se pueden setear las variables antes de hacer el if para acortar la sintaxis
```php
$old_subscription = get_post_meta($order->get_id(), 'mobbex_subscription', true);
$old_subscriber   = get_post_meta($order->get_id(), 'mobbex_subscriber', true);
```

2023-08-28 15:25 UTC, jlmobbex commented on includes/helper.php
> +                $subscription->uid            = $subscription_data['uid'];
Ya que estamos en un método de migración creo que estaría bueno migrar toda la data que podamos del objeto guardado por `post_meta`. Además, más abajo en el save se está editando la suscripción original, y muchos de estos campos están enviandose vacíos a Mobbex. Debería asegurarse que el reference, webhook_url, return_url y todos los datos que conforman la suscripción anterior se manden.

2023-08-28 15:25 UTC, jlmobbex commented on includes/class-subscription.php
Agregaría un comentario en el construct, en el param `$productId` que indique que puede recibir cualquier `post_id` en realidad para que se entienda el funcionamiento de las suscripciones migradas de la 2.x.

2023-08-28 15:25 UTC, jlmobbex commented on includes/helper.php
> +                $subscription->uid            = $subscription_data['uid'];
El nuevo reference podría no tener el timestamp, debido a que puede ser imposible encontrar el anterior en local

2023-08-28 15:25 UTC, jlmobbex commented on includes/gateway.php
>              if (Mbbx_Subs_Product::is_subscription($product_id) || WC_Subscriptions_Product::is_subscription($product)) {
Acá se verifica si es una suscripción standalone o de WCS, no sería sólo para standalone esta lógica? Al mismo tiempo pregunto, tiene sentido verificar que `$sub_options['type'] === 'dynamic'`?

2023-08-28 15:25 UTC, jlmobbex commented on includes/gateway.php
> +        if($this->helper->is_wcs_active()){
Yo armaría un nuevo método `MobbexSubscription::get_post_id` que contenga esta lógica que depende de la versión en la que fue creada la suscripción.

2023-08-28 15:25 UTC, jlmobbex commented on includes/helper.php
> +    public function create_mobbex_subscription($product_id, $sub_options, $id = null)
Acá recibe en duplicado el `post_id`. Podría recibir un sólo param, `post_id` al principio, o que se siga llemando `product_id` y que cuando se genera en base a un pedido que se mande por ese param.

2023-08-28 15:25 UTC, jlmobbex commented on includes/helper.php
> +    public function get_total($order)
En el checkout aparece como aplicado dos veces el descuento. Ej. si se configura un cupón de 10% sobre $70 se muestra $56 (debería mostrar $63).

2023-09-04 21:16 UTC, jlmobbex commented on includes/helper.php
> +    public function create_mobbex_subscription($product_id, $sub_options, $id = null)
Este tema quedó abierto, se sigue consultando en duplicado el dato, sólo que en vez de recibir el ID del pedido se trae directamente `$order`

2023-09-05 12:48 UTC, EMunozMobbex commented on includes/helper.php
> +    public function create_mobbex_subscription($product_id, $sub_options, $id = null)
No reemplazo el param product_id por post_id porque el product_id lo necesito en todos los casos, ya que requiero el objeto product para obtener tanto el precio, como el nombre y la descripción de la suscripción, podria pasarle si no el objeto de $order y $product en todos los casos

2023-09-05 12:57 UTC, EMunozMobbex commented on includes/helper.php
> +    public function create_mobbex_subscription($product_id, $sub_options, $id = null)
Quedaría así:

```php
    /**
     * Creates/Update a Mobbex Subscription & return Subscription class
     * 
     * @param object $product
     * @param array $sub_options
     * @param WC_Order|WC_Subscription $order
     * 
     * @return \MobbexSubscription|null
     */
    public function create_mobbex_subscription($product, $sub_options, $order = null)
    {
        $post_id  =  $this->get_post_id($product->get_id(), $order);
        $sub_name = $product->get_name();
        
        $subscription = new \MobbexSubscription(
            $post_id,
            "wc_order_{$post_id}",
            $product->get_price(),
            $sub_options['setup_fee'],
            $sub_options['type'],
            $sub_name,
            $sub_name,
            $sub_options['interval'],
            $sub_options['trial'],
            0,
        );

        if(!empty($subscription)){
            //Save Subscription 
            $subscription->save();
            return $subscription;
        }
```

        return null;
    }

2023-09-05 13:12 UTC, EMunozMobbex commented on includes/helper.php
> +    public function create_mobbex_subscription($product_id, $sub_options, $id = null)
Aproveche el $sub_options y quedaria asi:

```php

    /**
     * Creates/Update a Mobbex Subscription & return Subscription class
     * 
     * @param array $sub_options
     * 
     * @return \MobbexSubscription|null
     */
    public function create_mobbex_subscription($sub_options)
    {
        $subscription = new \MobbexSubscription(
            $sub_options['post_id'],
            $sub_options['reference'],
            $sub_options['price'],
            $sub_options['setup_fee'],
            $sub_options['type'],
            $sub_options['name'],
            $sub_options['name'],
            $sub_options['interval'],
            $sub_options['trial'],
            0,
        );

        if(!empty($subscription)){
            //Save Subscription 
            $subscription->save();
            return $subscription;
        }

        return null;
    }

```

2023-09-05 17:47 UTC, jlmobbex approved these changes

2023-09-05 17:47 UTC, merged