[ECO-462] Add activate - suspend subscriber from wcs
mobbexco/woocommerce-subscriptions pull request #45
Opened 2023-09-20 18:15 UTC by mobbexLuis

2023-09-22 16:27 UTC, EMunozMobbex requested changes

2023-09-22 16:27 UTC, EMunozMobbex commented on includes/gateway.php
> +            $subscriber = $wpdb->get_results(
Por ahi para apegarnos a la estructura orientada a objetos que venimos manejando en woo subs, lo ideal seria que obtengas el subscriber haciendo 
```php
$subscriber = new MobbexSubscriber($order_id);
```

2023-09-22 16:27 UTC, EMunozMobbex commented on includes/gateway.php
> +            $this->helper->update_subscription_status($subscriber[0]->subscription_uid, $subscriber[0]->uid, $status);
Un poco en la misma linea que el comentario anterior, el metodo
`update_subscription_status` quizá tendria mas sentido que fuera un metodo dentro de la clase MobbexSubscription de esa forma ademas nos ahorrariamos pasarle el subscription uid por param

2023-09-22 16:27 UTC, EMunozMobbex commented on includes/gateway.php
> +            $msg = $e->getMessage();
Hay alguna diferencia en asignar el mensaje a una variable? quiza es mejor pasar directamente `$e->getMessage()` al order note.

2023-09-22 16:27 UTC, EMunozMobbex commented on includes/helper.php
> +    public function update_subscription_status($subscription_uid, $subscriber_uid, $status)
Gran parte del codigo de este método se podria ahorrar utilizando la clase `\Mobbex\Api` por ejemplo toda la configuración de headers
solo tendrías que hacer 
```php
   \Mobbex\Api::request($data);
```

mandando en data la información correspondiente, el endpoint por ejemplo iria en `$data['uri']` y no requiere de `https://api.mobbex.com/p/` ya que ese primer tramo lo autocompleta.

2023-09-22 16:27 UTC, EMunozMobbex commented on includes/helper.php
> +            [$subscription_uid, $subscriber_uid], MOBBEX_SUSPEND_SUBSCRIBER),
Por otro lado quizá estaría bueno que la suspención del subscriber se haga desde un método dentro de la clase `MobbexSubscriber`, que podría en todo caso ser llamado por `MobebxSubscription` si el método de desactivar la sub recibe el objeto de subscriber en lugar del uid

2023-09-22 16:27 UTC, EMunozMobbex commented on includes/utils.php
> +define('MOBBEX_SUSPEND_SUBSCRIBER', 'https://api.mobbex.com/p/subscriptions/{uid}/subscriber/{sid}/action/suspend');
Usando la clase API del sdk es muy probable que ya no sean necesarias estas lineas

2023-09-25 12:15 UTC, mobbexLuis commented on includes/utils.php
> +define('MOBBEX_SUSPEND_SUBSCRIBER', 'https://api.mobbex.com/p/subscriptions/{uid}/subscriber/{sid}/action/suspend');
todavia no tenemos integrado el sdk pero lo estoy haciendo con la clase api del modulo

2023-09-25 13:31 UTC, mobbexLuis commented on includes/helper.php
> +            [$subscription_uid, $subscriber_uid], MOBBEX_SUSPEND_SUBSCRIBER),
ahora el método está dentro de MobbexSubscriber y se llama desde ahí.
no entiendo bien cuál seria el motivo por el cual deberia ser llamado por MobbexSubscription dado que es algo que afecta al subscriptor mas no a la subscipción. En todo caso lo seguimos viendo

2023-09-26 19:27 UTC, EMunozMobbex requested changes

2023-09-26 19:27 UTC, EMunozMobbex commented on includes/class-subscriber.php
> +            'subscriptions/{uid}/subscriber/{sid}/action/activate'
Tiene sentido usar un string_replace?

pienso que seria mas simple y mas legible:
```php
$uri = "subscriptions/{$this->subscription_uid}/subscriber/{$this->uid}/action/activate";
```

2023-09-26 19:27 UTC, EMunozMobbex commented on includes/class-subscriber.php
> +                'subscriptions/{uid}/subscriber/{sid}/action/suspend'
En la misma linea de lo anterior incluso creo que se podría reducir mas así:
```php
$action = $status == 'on-hold' ? 'suspend' : 'activate';
$uri = "subscriptions/{$this->subscription_uid}/subscriber/{$this->uid}/action/{$action}";
```

Me queda la pregunta de si status podria tener algo que no sea `on-hold` y `active`

2023-09-26 19:27 UTC, EMunozMobbex commented on includes/class-subscriber.php
> +    public function update_subscription_status($status)
Quizá podría llamarse update_status el método, o de otra manera que indique que la suscripcion se desactiva solo para ese suscriptor, ya que lo que actualiza es el estado de la suscripción en el suscriptor y no el estado de la suscripción en si ( si no, la desactivaría para todos los suscriptores ya que ahora una suscripción puede tener múltiples suscriptores)

2023-09-26 19:42 UTC, EMunozMobbex commented on includes/class-subscriber.php
> +            'uri'    => $uri
Incluso se podria colocar la ```$uri``` acá sin asignarla a una variable y solo asignar el $action.

2023-09-26 21:35 UTC, EMunozMobbex approved these changes

2023-09-27 15:00 UTC, jlmobbex requested changes

2023-09-27 15:00 UTC, jlmobbex commented on includes/gateway.php
> +    public function update_state_endpoint($subscription)
Este no sería en si un endpoint propio.

2023-09-27 15:00 UTC, jlmobbex commented on includes/gateway.php
> +            $order_id   = $subscription->get_parent()->get_id();
Agreguemos un chequeo de que `get_parent` y `$subscription` no sean null. En caso de que lo sean se hace un `throw \Exception`. Por otro lado recordá siempre usar la barra lateral antes del nombre de una clase (en este caso sería `\MobbexSubscriber`) para evitar errores por namespaces relativos.

2023-09-28 03:35 UTC, jlmobbex approved these changes

2023-09-28 03:36 UTC, merged