[ECO-584] Add composer update checker
mobbexco/woocommerce-subscriptions pull request #53
Opened 2023-10-31 16:42 UTC by mobbexLuis

2023-11-03 20:32 UTC, jlmobbex requested changes

2023-11-03 20:32 UTC, jlmobbex commented on build.sh
> +# Install dependencies
Esto no va a ser necesario ya que va a utilizarlas dependencias del plugin principal, incluyendo el update checker y el SDK.

2023-11-03 20:32 UTC, jlmobbex commented on composer.json
> +{
Mismo comentario, esta dependencia ya se trae al incluir el autoload del plugin principal, que la requiere

2023-11-06 13:22 UTC, EMunozMobbex approved these changes

2024-03-01 14:38 UTC, jlmobbex approved these changes

2024-03-01 14:38 UTC, merged