[ECO-217] Php plugin sdk integration
mobbexco/woocommerce-subscriptions pull request #56
Opened 2023-11-13 14:52 UTC by mobbexLuis

2024-01-30 18:54 UTC, jlmobbex requested changes

2024-01-30 18:54 UTC, jlmobbex commented on mobbex-subs-for-woocommerce.php
> +require_once WP_PLUGIN_DIR . '/woocommerce-mobbex/Model/Db.php';
Estos `require` no son necesarios ya que el autoload del plugin de checkout automáticamente carga los archivos

2024-01-30 18:54 UTC, jlmobbex commented on mobbex-subs-for-woocommerce.php
> +require_once 'Model/model.php';
Puede usarse directamente el modelo que está en el plugin de checkout. Habría revisar que ambos sean totalmente compatibles al realizar la transición.

2024-01-30 18:54 UTC, jlmobbex commented on mobbex-subs-for-woocommerce.php
> +require_once WP_PLUGIN_DIR . '/woocommerce-mobbex/vendor/autoload.php';
Este autoload estaría bueno que se ubique arriba del resto de clases, por si alguna extiende de alguna que carga el autoload

2024-02-07 13:04 UTC, mobbexLuis commented on mobbex-subs-for-woocommerce.php
> +require_once 'Model/model.php';
visto con Javi, resuelto. El modelo se queda

2024-03-06 20:57 UTC, merged