[ECO-670] Fix subscription saving when publishing subscription product
mobbexco/woocommerce-subscriptions pull request #57
Opened 2023-12-04 19:08 UTC by mobbexLuis

2023-12-06 02:56 UTC, jlmobbex requested changes

2023-12-06 02:56 UTC, jlmobbex commented on includes/admin/product-settings.php
> +            add_action('wp_after_insert_post', [self::class, 'create_mobbex_sub_integration_wcs']);
Este hook se dispara después de guardar cualquier post desde el panel de administración, incluyendo pedidos, páginas, etc. Hay que adaptar el funcionamiento para comprobar que sólo se dispare cuando se guarda el producto.

No habrá un hook específico para productos como con `woocommerce_process_product_meta`? Se pudo entender por qué este no funciona?

2023-12-06 13:52 UTC, mobbexLuis commented on includes/admin/product-settings.php
> +            add_action('wp_after_insert_post', [self::class, 'create_mobbex_sub_integration_wcs']);
En el método 'create_mobbex_sub_integration_wcs', línea 223 se hace una comprobacion mediante $post_id (`WC_Subscriptions_Product::is_subscription( $post_id )`) para verificar que el post sea tipo subscripción. En caso contrario no se crea $subscription y no se guarda.
Se me ocurre que podemos hacer esa verificación al principio del método para bypassear el resto del funcionamiento en caso que no sea una subscripción.

Respecto al hook específico para productos, encontré 'woocommerce_rest_insert_product_object' pero no di con documentación que detalle el funcionamiento del mismo.

2023-12-06 21:24 UTC, jlmobbex requested changes

2023-12-06 21:24 UTC, jlmobbex commented on includes/admin/product-settings.php
> +        if(!WC_Subscriptions_Product::is_subscription( $post_id ))
Recordá que primero debe chequearse que WCS esté activo, porque sino sería posible que la clase `WC_Subscriptions_Product` no exista (para integraciones standalone). Quedaría así:
`if(self::$helper->is_wcs_active() && WC_Subscriptions_Product::is_subscription( $post_id ));`

2023-12-14 03:01 UTC, jlmobbex requested changes

2023-12-14 03:01 UTC, jlmobbex commented on includes/admin/product-settings.php
> +        if(self::$helper->is_wcs_active() && !WC_Subscriptions_Product::is_subscription($post_id));
Así como está, se crea la suscripción cuando wcs se encuentra desactivado, y también cuando está activado y el producto es de tipo suscripción. Al voltearse la condición el `&&` también se tiene que voltear. Siempre que las condiciones se transforman en condiciones de guarda hay que revisar muy profundamente cada operador:
```php
if(!self::$helper->is_wcs_active() || !WC_Subscriptions_Product::is_subscription($post_id))
```

2023-12-19 19:48 UTC, EMunozMobbex approved these changes

2023-12-22 19:00 UTC, jlmobbex commented on includes/admin/product-settings.php
> +        if(self::$helper->is_wcs_active() && !WC_Subscriptions_Product::is_subscription($post_id));
@mobbexLuis Esto aún no quedó resuelto

2023-12-22 19:01 UTC, jlmobbex requested changes
El comentario anterior no quedó resuelto

2023-12-27 18:05 UTC, mobbexLuis commented on includes/admin/product-settings.php
> +        if(self::$helper->is_wcs_active() && !WC_Subscriptions_Product::is_subscription($post_id));
listo! no sé por qué habia quedado sin corregir el operador
gracias Javi

2024-01-25 14:13 UTC, jlmobbex requested changes

2024-01-25 14:13 UTC, jlmobbex commented on includes/admin/product-settings.php
> +        if(!self::$helper->is_wcs_active() || !WC_Subscriptions_Product::is_subscription($post_id));
`is_subscription` chequea que la suscripción de tipo standalone esté activa, pero este método tiene la funcionalidad de guardar suscripciones integradas con WooCommerce Subscriptions. Tendría que chequearse que el producto sea de tipo suscripción simple. Este probablemente sea el motivo por el que a los comercios no les funciona.

2024-02-08 20:08 UTC, EMunozMobbex approved these changes

2024-02-16 13:53 UTC, jlmobbex requested changes

2024-02-16 13:53 UTC, jlmobbex commented on includes/admin/product-settings.php
> +            return;
Me parece mejor idea usar `!WC_Subscriptions_Product::is_subscription($post_id));`. Que hasta dónde investigue realiza más verificaciones, como si es un objeto `$product`, y si es una suscripción variable. Por qué se cambió a este enfoque?

2024-02-16 19:50 UTC, mobbexLuis commented on includes/admin/product-settings.php
> +            return;
corregido :)

2024-02-16 21:11 UTC, jlmobbex approved these changes

2024-02-16 21:12 UTC, merged