[ECO-1137] Added subscriber verification when updating their status
mobbexco/woocommerce-subscriptions pull request #75
Opened 2024-11-01 19:45 UTC by mobbexLuis

2024-12-04 14:48 UTC, EMunozMobbex approved these changes

2025-03-06 17:09 UTC, jlmobbex requested changes

2025-03-06 17:09 UTC, jlmobbex commented on gateway.php
>                  throw new \Exception(__('Mobbex error: Subscription or parent order not found on state update', 'mobbex-subs-for-woocommerce'));
Acá había una validación sobre `$subscription`, es importante mantenerla porque podría ser null

2025-03-12 13:54 UTC, jlmobbex approved these changes

2025-03-12 13:55 UTC, merged