[ECO-1169] Fixed scheduled payment total update
mobbexco/woocommerce-subscriptions pull request #83
Opened 2024-12-03 18:21 UTC by mobbexLuis

2024-12-04 14:47 UTC, EMunozMobbex reviewed
No llevaria a cabo este cambio ya que en las manuales corresponde que los totales y la agenda los administre WCS y no nosotros, por ende el total siempre debe tomarse de la orden.

2024-12-05 20:59 UTC, jlmobbex requested changes

2024-12-05 20:59 UTC, jlmobbex commented on includes/gateway.php
> +            $total = $subscription->total;
Entiendo que lo que se busca en esta PR es actualizar el objeto suscripción que se guarda en base de datos, cambiando el total por el que viene como parámetro. Si es así, no se está realizando el guardado de subscription, y se está ejecutando con el total antiguo

2024-12-06 13:52 UTC, mobbexLuis commented on includes/gateway.php
> +            $total = $subscription->total;
En principio se buscaba "corregir" el total de la subscripción para que sea el que corresponde, pero resolvimos que es un manejo del que es responsable woocommerce (ya que es el total que pasa en el hook)
Aclaro que la sugerencia del fix fue algo que surgió en pruebas, no fue informado por clientes

2024-12-06 14:00 UTC, jlmobbex commented on includes/gateway.php
> +            $total = $subscription->total;
Perfecto, cerramos la PR entonces!

2024-12-06 14:01 UTC, closed without merging